### ISSUE TITLE
udp response destaddress and destport fault

### ISSUE THREAD

**Issue by grayscott** [txthinking/socks5#3]
#### Steps to reproduce the problem
0.
1.
2.

**Comment by grayscott** [comment]
udp response destaddress and destport should be connect dest address and port
			a, addr, port, err := ParseAddress(ue.RemoteConn.RemoteAddr().String())
			if err != nil {
				log.Println(err)
				break
			}
			d1 := NewDatagram(a, addr, port, b[0:n])
			if _, err := s.UDPConn.WriteToUDP(d1.Bytes(), ue.ClientAddr); err != nil {
				break
			}

**Comment by txthinking** [comment]
It's not, here is write data to client.
please test and run and **provide minimize reproduce code** and *its logs* if anything is unexpected.

**Comment by txthinking** [comment]
It looks you are right, PR please

**Comment by txthinking** [comment]
I am not sure this.
The RFC doesn't describe this addr when socks5 reply to udp client.

Based RFC1928, we can guess the intention. When a socks5 client want to send UDP, then:

1. client prepare a UDP address `A` (that the client expects
   to use to send UDP datagrams)
2. server send a address `B`(tell client should send data to)
3. client use `A` send data to `B`
4. server send data to remote and get data from remote data
5. server send data to client, and write a `address` in datagram, so I think this `address` should be `A`, so client can pair `this data` cause by `which send`

**Comment by 0990** [comment]
RFC1928 say " when a UDP relay server receives a replay datagram from a remote host,it must encapsulate that datagram using the above UDP request header",so I guess grayscott is right
1,TCP: client prepares a UDP address A (that the client expects
to use to send UDP datagrams)
2,TCP: server sends a address B(tell client should send data to)
3,UDP: client uses A send data to B and write a address C in datagram,C means remote target
4,UDP: server sends data to remote C and get data from remote C
5,UDP: server sends data to client, and write a address in datagram, so I think this address should be C, so client can pair this data cause by which send

**Comment by 0990** [comment]
I test ss5(http://ss5.sourceforge.net/),found the address udp datagram returned to client is C

**Comment by txthinking** [comment]
@0990 Thank you.
