### ISSUE TITLE
A UDP association terminates when the TCP connection that the UDP ASSOCIATE request arrived on terminates 

### ISSUE THREAD

**Issue by Danieldachao** [txthinking/socks5#4]
//A UDP association terminates when the TCP connection that the UDP ASSOCIATE request arrived on terminates.

**Comment by Danieldachao** [comment]
it seems that you haven't  implemented this function yet?

**Comment by txthinking** [comment]
Thx, I am working on this function.

**Comment by txthinking** [comment]
Before check this issue, we must strictly associate the UDP and TCP connection, #5

**Comment by txthinking** [comment]
just set `Server.LimitUDP = true`
